default:
   paths:
       features: '../features/single'
       bootstrap:  '../features/bootstrap'
   context:
       parameters:
           lambdatest:
               server: "hub.lambdatest.com"
               user: "YOUR LT_USERNAME"
               key: "YOUR LT_ACCESS_KEY"

               capabilities:
                   build: "behat-selenium-sample"
                   name: "parallel-behat-test"

               environments:
                   -
                       browserName: chrome
                       version: latest
                       platform: Windows 10
                   -
                       browserName: chrome
                       version: latest-1
                       platform: Windows 10
                   -
                       browserName: chrome
                       version: latest-2
                       platform: Windows 10
                   -
                       browserName: chrome
                       version: latest-3
                       platform: Windows 10
                   -
                       browserName: chrome
                       version: latest-4
                       platform: Windows 10
