default:
    autoload:
        '': '%paths.base%/../features/bootstrap'
    suites:
        default:
            paths: [ '%paths.base%/../features' ]
            contexts:
                - FeatureContext:
                    parameters:
                        server: "hub.lambdatest.com"
                        user: "YOUR LT_USERNAME"
                        key: "YOUR LT_ACCESS_KEY"
                        capabilities:
                            # common capabilities added for every test
                            build: "behat-selenium-sample"
                        environments:
                            # each capability in this list is execute as single test
                            # so to run multiple tests in parallel,
                            # simply define multiple capabilities below and execute the test with
                            # $ php run-parallel.php -c config/<filename>.yml
                        -
                            browserName: chrome
                            browserVersion: latest
                            platformName: Windows 10
                            name: "parallel behat test latest"
                        -
                            browserName: chrome
                            browserVersion: latest-1
                            platformName: Windows 10
                            name: "parallel behat test latest-1"
                        -
                            browserName: chrome
                            browserVersion: latest-2
                            platformName: Windows 10
                            name: "parallel behat test latest-2"
                        -
                            browserName: chrome
                            browserVersion: latest-3
                            platformName: Windows 10
                            name: "parallel behat test latest-3"
                        -
                            browserName: chrome
                            browserVersion: latest-4
                            platformName: Windows 10
                            name: "parallel behat test latest-4"
                    