default:
    autoload:
        '': '%paths.base%/../features/bootstrap'
    suites:
        default:
            paths: [ '%paths.base%/../features' ]
            contexts:
             - FeatureContext:
                    parameters:
                        server: "hub.lambdatest.com"
                        user: "YOUR LT_USERNAME"
                        key: "YOUR LT_ACCESS_KEY"
                        capabilities:
                            build: "behat-selenium-sample"
                            name: "single-behat-test"
                        environments:
                            -
                                browserName: chrome
                                browserVersion: latest
                                platformName: Windows10


